apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
data:
  postgresqlUser: {{ .Values.postgresqlSecret.postgresqlUser | b64enc | quote }}
  postgresqlPassword: {{ .Values.postgresqlSecret.postgresqlPassword | b64enc | quote }}